FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8089 8000

CMD ["locust", "-f", "tests/locustfile.py", "--web-port", "8089"]
