jobs:
  run-locust:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run API server in background
        run: |
          # Inicia tu servidor de API y lo redirige a un archivo de registro
          python tu_servidor_de_api.py &> server.log &

      - name: Run Locust load test
        run: locust -f tests/locustfile.py --headless -u 10 -r 1 --run-time 1m --host http://localhost
