name: Locust Load Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-locust:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        architecture: x64

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Locust load test
      run: |
       locust -f tests/locustfile.py --headless -u 10 -r 1 --run-time 1m

    - name: Upload reports as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: locust-report
        path: reports/
